package costants;

import java.awt.*;

public class Colors {

    private Colors(){}

    public static final Color[] distinctColors = {
            Color.decode("#000000"),
            Color.decode("#00FF00"),
            Color.decode("#0000FF"),
            Color.decode("#FF0000"),
            Color.decode("#01FFFE"),
            Color.decode("#FFA6FE"),
            Color.decode("#FFDB66"),
            Color.decode("#006401"),
            Color.decode("#010067"),
            Color.decode("#95003A"),
            Color.decode("#007DB5"),
            Color.decode("#FF00F6"),
            Color.decode("#FFEEE8"),
            Color.decode("#774D00"),
            Color.decode("#90FB92"),
            Color.decode("#0076FF"),
            Color.decode("#D5FF00"),
            Color.decode("#FF937E"),
            Color.decode("#6A826C"),
            Color.decode("#FF029D"),
            Color.decode("#FE8900"),
            Color.decode("#7A4782"),
            Color.decode("#7E2DD2"),
            Color.decode("#85A900"),
            Color.decode("#FF0056"),
            Color.decode("#A42400"),
            Color.decode("#00AE7E"),
            Color.decode("#683D3B"),
            Color.decode("#BDC6FF"),
            Color.decode("#263400"),
            Color.decode("#BDD393"),
            Color.decode("#00B917"),
            Color.decode("#9E008E"),
            Color.decode("#001544"),
            Color.decode("#C28C9F"),
            Color.decode("#FF74A3"),
            Color.decode("#01D0FF"),
            Color.decode("#004754"),
            Color.decode("#E56FFE"),
            Color.decode("#788231"),
            Color.decode("#0E4CA1"),
            Color.decode("#91D0CB"),
            Color.decode("#BE9970"),
            Color.decode("#968AE8"),
            Color.decode("#BB8800"),
            Color.decode("#43002C"),
            Color.decode("#DEFF74"),
            Color.decode("#00FFC6"),
            Color.decode("#FFE502"),
            Color.decode("#620E00"),
            Color.decode("#008F9C"),
            Color.decode("#98FF52"),
            Color.decode("#7544B1"),
            Color.decode("#B500FF"),
            Color.decode("#00FF78"),
            Color.decode("#FF6E41"),
            Color.decode("#005F39"),
            Color.decode("#6B6882"),
            Color.decode("#5FAD4E"),
            Color.decode("#A75740"),
            Color.decode("#A5FFD2"),
            Color.decode("#FFB167"),
            Color.decode("#009BFF"),
            Color.decode("#E85EBE")
    };
}
